/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,css}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#bb0024',
        'primary-container': '#e41b34',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#410006',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b0',
        'on-primary-fixed-variant': '#93001a',
        secondary: '#775a00',
        'secondary-container': '#ffc72c',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6f5400',
        'secondary-fixed': '#ffdf99',
        'secondary-fixed-dim': '#f6bf22',
        'on-secondary-fixed': '#251a00',
        'on-secondary-fixed-variant': '#5a4300',
        tertiary: '#00694d',
        'tertiary-container': '#008562',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f5fff8',
        'tertiary-fixed': '#54fdc4',
        'tertiary-fixed-dim': '#27e0a9',
        'on-tertiary-fixed': '#002116',
        'on-tertiary-fixed-variant': '#00513b',
        surface: '#fcf9f8',
        'surface-container': '#f0edec',
        'surface-container-low': '#f6f3f2',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-tint': '#bf0025',
        background: '#fcf9f8',
        'on-background': '#1c1b1b',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#5d3f3e',
        outline: '#926e6d',
        'outline-variant': '#e6bdba',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'inverse-primary': '#ffb3b0',
        comicYellow: '#FFE600',
        comicRed: '#FF3344',
        comicBlue: '#00D2FF',
        comicGreen: '#00E676',
        comicOrange: '#FF7A00',
        paperBg: '#FDFBF7'
      },
      fontFamily: {
        'headline-sm': ['"Bricolage Grotesque"', 'sans-serif'],
        'headline-md': ['"Bricolage Grotesque"', 'sans-serif'],
        'headline-lg': ['"Bricolage Grotesque"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero': ['Bangers', '"Bricolage Grotesque"', 'cursive'],
        'label-comic-pill': ['Bangers', '"Bricolage Grotesque"', 'cursive'],
        'comic-score': ['Bangers', 'cursive']
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '26px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '700' }],
        'label-lg': ['16px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '700' }],
        'display-hero': ['56px', { lineHeight: '60px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'label-comic-pill': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '800' }]
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px'
      },
      borderWidth: { '2.5': '2.5px', '3': '3px' },
      boxShadow: {
        'comic-sm': '2px 2px 0px #1c1b1b',
        'comic-md': '3px 3px 0px #1c1b1b',
        'comic-lg': '4px 4px 0px #1c1b1b',
        'comic-xl': '6px 6px 0px #1c1b1b'
      }
    }
  },
  plugins: []
};
